spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:./temp/test;AUTO_SERVER=TRUE

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2
