spring:
  thymeleaf:
    cache: false

  application:
    name: path-finder

  datasource:
    url: jdbc:h2:E:/Projects/Java/DB/H2/test;AUTO_SERVER=TRUE

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka