DROP TABLE IF EXISTS Area;

CREATE TABLE IF NOT EXISTS Area (
    id identity,
    type VARCHAR(200) NOT NULL,
    content VARCHAR(200) NOT NULL,
    L DOUBLE NOT NULL,
    T DOUBLE NOT NULL,
    B DOUBLE NOT NULL,
    R DOUBLE NOT NULL,
    TreasureMap_id LONG NOT NULL
);

DROP TABLE IF EXISTS TreasureMap;

CREATE TABLE IF NOT EXISTS TreasureMap (
    id identity,
    name VARCHAR(200) NOT NULL
);